config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users
  get '/aboutme' => 'users#aboutme'
  get '/projects' => 'users#projects'
  get '/portfolio' => 'users#portfolio'
  get '/resume' => 'users#resume'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
	end

	def new
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
	def new
    	@contact = Contact.new
  	end

  	def create
    	@contact = Contact.new(params[:contact])
    	@contact.request = request
    	if @contact.deliver
      		flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    	else
      		flash.now[:error] = 'Cannot send message.'
      		render :new
    	end
  	end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
		render 'show'
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/index.html.erb
<div class="blogpage" style="height:50em;">

	<div class="leftblogpage" style="width:49%;height:100%;float:left">
		<h2 style="padding-top:4em;text-align:center;color:white">Tech Blog</h2>
			<ul style="text-align:center;">
				<li>Git</li>
				<li>Css Design</li>
				<li>Arrays - Hashes</li>
				<li>Enumerables</li>
				<li>Ruby Classes</li>
				<li>OOP- Concepts</li>
				<li>Javascript</li>
				<li>Tech</li>
			</ul>
	</div>

	<div class="rightblogpage" style="width:49%;height:100%;float:right">
		<h2 style="padding-top:4em;text-align:center;color:white">Cultural Blog</h2>
			<ul style="text-align:center;">
				<li>Chef's-Kitchen</li>
				<li>Thinking-Style</li>
				<li>Tech-Issues</li>
				<li>Feedback</li>
				<li>Stereotype-Threat</li>
				<li>Values</li>
				<li>Conflict</li>
				<li>Questions</li>
			</ul>
	</div>

</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
</header>
<div class="contactpage" style="text-align:center;">


  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %><br>
    <%= f.input :email, :required => true %><br>
    <%= f.input :message, :as => :text, :required => true %><br>
<!--     <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div> -->
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-default learnmorebutton" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <!-- bootstrap cdn -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  

  <!-- google font -->

  <link  href="http://fonts.googleapis.com/css?family=Cabin:400,500,600,bold" rel="stylesheet" type="text/css" >
  <link  href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:regular,bold" rel="stylesheet" type="text/css" >

  <!-- jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <!-- jquery UI -->
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

  <!-- google font -  Source Sans Pro -->
  
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header>
  
  <nav class='navbar transparent navbar-inverse navbar-fixed-top'>
    <nav class="navbar-inner">
      <div class="container contact">
        <%= link_to 'Contact', contacts_path %>
        <%= link_to 'Blog', blogs_path %>
        <%= link_to 'Portfolio', portfolio_path %>
        <%= link_to 'Resume', resume_path %>
        <%= link_to 'Home', root_path , class: 'home'%>
      </div>
<!--  <div class='container' id='navigate'>
      <a href='https://twitter.com/br1anp4rk718'>
      <img src='http://youngist.org/images/icon-social-twitter.svg' class='icon' alt='twitter' style='width:30px;height:35px;'></a>
      <a href="mailto:br1anp4rk718@gmail.com"><img src='https://cdn0.iconfinder.com/data/icons/seo-smart-pack/128/grey_new_seo-15-512.png' class='icon' style='width:30px;height:35px;'></a>
      <a href='https://www.facebook.com/brian.park.319'><img src='http://moznostvolby.sk/wp-content/uploads/2014/05/facebook-icon-white.png' class='icon' style='width:30px;height:35px;'></a>
      <a href='https://github.com/br1anp4rk718'><img src='http://jeremyzander.com/images/github.png' class='icon' style='width:30px;height:35px;'></a>
      </div> -->
      </nav>
    </nav>

</header>



<body>

<%= yield %>

  <%= javascript_include_tag "texthover" %>
 <%= javascript_include_tag "slidescreen" %>
</body>
</html>

app/views/users/contact.html.erb
<div class="contactpage">



</div>

app/views/users/index.html.erb
<div class="enterpage" id="frontpage" style="z-index:200">
	<div class="leftarrow" style="width:20%"><%= link_to "#{image_tag('leftarrow.png')}".html_safe, :controller => :welcome, :action => "index" %>
	</div>
				
	<div class="aboutmedescription" style="text-align:center;margin-top:9em; color:aliceblue; font-size:25px;font-family:fantasy">Name: Brian Park<br>Age:29<br>		Birthdate: July 18th, 1986<br>Nationality: Korean-American<br>		Passion:Building beautiful and meaningful applications<br>			Basketball Fanatic
	</div>
	<div class="rightarrow" style="width:20%"><%= image_tag 'rightarrow' %>
	</div>
</div>
 
<div class="enterpage" id="aboutme2" style="">
	<div class="leftarrow" style="width:20%">
		<%= image_tag 'leftarrow' %>
	</div>
				
	<div class="aboutmedescription" style="text-align:center;margin-top:9em; color:aliceblue;font-family:fantasy;font-size:20px;">The ability to be able to create applications from scratch - that's what made me fall in love with code.<br>I first started to self teach myself during the summer of 2014. As I learned more and began to create applications from the back end all the way to front end, the realm of possibilities of what I can accomplish seemed endless. I was hooked. Soon after I decided that I needed to take the next step and accelerate my learning. That is when I chose to attend Dev Bootcamp<br><br>
	DBC is where I learned the necessary skills to call myself a full stack developer, learning various stacks of technology, and developed many applications on both the server side and front end, to be able to create meaningful and practical applications
	</div>
	<div class="rightarrow" style="width:20%"><%= image_tag 'rightarrow' %>
	</div>
</div>


<div class="enterpage" id="projects" style="z-index:-1">
	<div class="leftarrow" style="width:20%">
		<%= image_tag 'leftarrow' %>
	</div>
				
	<div class="aboutmedescription" style="text-align:center;margin-top:9em; color:aliceblue; font-size:25px;font-family:fantasy">
		Click to see list of projects
	</div>
	<div class="rightarrow" style="width:20%"><%= image_tag 'rightarrow' %>
	</div>
</div>

app/views/users/portfolio.html.erb
<div class="portfolio">

	<div id="gallery" style="padding-top:3em">
            <a href="http://shop-nfc.com/" id="new"></a>
            <a href="2" class="preowned"></a>
            <a href="3" class="serviceparts"></a>
            <a href="4" class="specials"></a>
            <a href="5" class="diamond"></a>
    </div>

</div>

app/views/users/projects.html.erb
<div class="enterpage" id="projects">
	<div class="leftarrow" style="width:20%"><%= link_to "#{image_tag('leftarrow.png')}".html_safe, :controller => :welcome, :action => "index" %>
	</div>
				
	<div class="aboutmedescription" style="text-align:center;margin-top:9em; color:aliceblue; font-size:25px;font-family:fantasy">
		Click to see list of projects
	</div>
	<div class="rightarrow" style="width:20%"><%= image_tag 'rightarrow' %>
	</div>
</div>

app/views/users/resume.html.erb
<div class="container">



</div>

app/views/welcome/index.html.erb
<div class="container landing-page">

	<div class = "left" style="float: left; width:26%; height:50em;opacity:0.5">

	</div>

		

			<div class="aboutme" style="text-align:center;">
			<%= link_to "Learn More", users_path, class: "btn btn-default learnmorebutton" %>
		
			</div>
			
			<div class="copyright">
				&copy; Brian Park 2015
			</div>
		
	
</div>